extends Node

onready var Sword = load("res://Items/Sword/Sword.tscn")

enum RARITY { BASIC, COMMON, UNCOMMON, RARE, EPIC }

enum MATERIAL_TYPE { GEM, METAL, WOOD, FABRIC }
enum MATERIAL_WEIGHT { VERY_LIGHT, LIGHT, MEDIUM, HEAVY, VERY_HEAVY }

enum PART_TYPE { SWORD_BLADE, SWORD_HANDLE, POMMEL }

enum ITEM_TYPE { WEAPON, ARMOR }
enum ITEM_SUBTYPE { SWORD, AXE, BODY_ARMOR, BOOTS, HELMET}
